Frans
informalr/informalr pull request #115
Opened 2020-11-17 19:06 UTC by fransbianchi

issue 94 done

2020-11-19 09:30 UTC, richelbilderbeek requested changes
Brilliant works, except for an accidentally deleted line. I suggest you add the line again, then resubmit :+1:

2020-11-19 09:30 UTC, richelbilderbeek commented on R/create_map.R
> -    data <- informalr::get_bridge_openings()
Deleting this line seems like an error to me. I suggest to put it back first :grin: :+1:

2020-11-24 17:55 UTC, fransbianchi commented
I have fixed the issue added the deleted line and the param on top

2020-11-24 17:58 UTC, richelbilderbeek approved these changes
Brilliant work :+1:

2020-11-24 17:59 UTC, merged